# Generated by Django 5.2.6 on 2025-09-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.FileField(max_length=155, upload_to='student/'),
        ),
    ]
