# Generated by Django 5.2.6 on 2025-09-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='Session',
            new_name='session',
        ),
    ]
