# Generated by Django 5.2.6 on 2025-09-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedtype', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=255)),
                ('sid', models.CharField(max_length=30)),
            ],
        ),
    ]
